version: "3"
services:
  mongo:
    image: "mongo"
    container_name: "coco-home-db"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: mongod --auth --port ${DB_PORT}
    volumes:
      - mongo-storage:/data/db
    networks:
      - coco-home-network
  coco-home-api:
    container_name: "coco-home-api"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - coco-home-network
networks:
  coco-home-network:
    driver: bridge
volumes:
  mongo-storage: {}
